### ISSUE TITLE
Add mossland project using Loom SDK in help page

### ISSUE THREAD

**Issue by cobject** [loomnetwork/loom-sdk-documentation#122]
Add mossland project using Loom SDK in [help page](http://localhost:3000/developers/en/help.html).

Your medium posting is [here](https://medium.com/loom-network/loom-sdk-projects-moss-pop-and-moss-store-are-bringing-augmented-reality-ar-mobile-applications-ebe78be71fc0)

Mossland project url is [here](https://moss.land/).

**Comment by mattkanwisher** [comment]
Open a PR and we will add it

**Comment by cobject** [comment]
Thanks, I notified it to mossland team.
