### ISSUE TITLE
[Request] Loom release version management

### ISSUE THREAD

**Issue by cobject** [loomnetwork/loom-sdk-documentation#132]
Dear @mattkanwisher,

Every new release, you need to change download url for loom binary in all repository’s readme file and dev page.

It is not comfortable to maintain, so I suggest that you’d better get a url always pointing to latest version of loom like below.

(example)
https://private.delegatecall.com/loom/osx/build-latest/loom

is now exactly same as

https://private.delegatecall.com/loom/osx/build-404/loom.

This make it easier to download latest version of loom any time and reduce useless commits to change version of loom, less conflicts for developer.

Thanks

**Comment by mattkanwisher** [comment]
we only release versions we are 100% sure that went through a QA cycle/ deployment onto our own clusters

**Comment by cobject** [comment]
As I mentioned above, build-latest means pointing to the latest verified version passed QA not just a latest build in your CI machine.
My proposal is that you could provide url for specific version and another url for the latest-verified version.

Thank for your feedback, @mattkanwisher

**Comment by mattkanwisher** [comment]
Good Idea we can have /build-latest/ and /build-stable/

**Comment by cobject** [comment]
correct.

**Comment by cobject** [comment]
applied.
