### ISSUE TITLE
Loom Unity SDK link is broken

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/loom-sdk-documentation#204]
URL: http://stage.loomx.io/developers/en/etherboy-game.html#game-controls

Broken Url: http://stage.loomx.io/developers/en/unity-sdk.html

Video:
![2019-05-17_13h43_58](https://user-images.githubusercontent.com/23660413/57913297-f06d1e80-78a9-11e9-8c8f-57f715989244.gif)

**Comment by Kanavs27** [comment]
Fixed
