### ISSUE TITLE
Mailing list option is missing from mobile devices

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/loom-sdk-documentation#206]
Note: This screen show is from Chrome/Desktop

![image](https://user-images.githubusercontent.com/23660413/57915558-ad617a00-78ae-11e9-89ce-a8e4db3945cd.png)

Screen shot from iPhone
![image](https://user-images.githubusercontent.com/23660413/57915748-0c26f380-78af-11e9-8112-d456c02ba286.png)

**Comment by HangYang** [comment]
fixed
![image](https://user-images.githubusercontent.com/3389447/66740675-53d59980-eea6-11e9-85bb-adeee4b1f4de.png)
