### ISSUE TITLE
Loom SDK Docs link redirects to old incorrect favicon page

### ISSUE THREAD

**Issue by Kanavs27** [loomnetwork/loom-sdk-documentation#225]
Go to http://stage.loomx.io/developers/en/cocos-sdk-quickstart.html#install-loom

Incorrect Favicon page https://loomx.io/developers/en/prereqs.html

Video: https://slack-files.com/T7AB1S3LN-FK0PSSJFP-be243bd6b6

![image](https://user-images.githubusercontent.com/44959753/58403878-65e2a700-8081-11e9-96f0-425bb1c45dce.png)

**Comment by Kanavs27** [comment]
Ok @Jangmingjin I think that URL redirects to prod that's why incorrect favicon is coming

**Comment by andreipope** [comment]
This page was removed anyways.

**Comment by mattkanwisher** [comment]
More pages were found in google not working

**Comment by andreipope** [comment]
Can I help in some way?

**Comment by HangYang** [comment]
@andreipope @Kanavs27 so this should be fixed.. since all old/not working pages will be redirect to loomx.io now
