### ISSUE TITLE
Dev deploy instructions 

### ISSUE THREAD

**Issue by sidharth747** [loomnetwork/loom-sdk-documentation#238]
Draft:
We go here, https://dev-dashboard.dappchains.com/add-key. first, you will click on generate a new public address. then, you will copy and paste the mnemonic and the public address. put the mnemonic somewhere safe.  paste the address and click add key. you will be asked to stake (or pay?) some amount of loom (10?). lastly, you’ll use the mnemonic to deploy with truffle. i’m going to show them how to add the mnemonic to truffle-config.js.

**Comment by andreipope** [comment]
PR: https://github.com/loomnetwork/loom-sdk-documentation/pull/240
