### ISSUE TITLE
Fix the PlasmaChain Testnets documentation/TG addresses

### ISSUE THREAD

**Issue by Nayeem1516** [loomnetwork/loom-sdk-documentation#243]
We have a previous ticket for this - https://github.com/loomnetwork/loom-sdk-documentation/issues/184

Not sure if this was fixed but let's take a look at it and if not we should get this in to-do. The previous issue is closed so I created this new one for tracking. 

According to a comment from SORARE - still the addresses have issues ->

### Preview
Pierre, [19.06.19 16:18]
hello. can you confirm that the ethereum transfer gateway address is 0x223CA78df868367D214b444d561B9123c018963A ?

Pierre, [19.06.19 16:18]
I'm starting the tests on mainnet

Pierre, [19.06.19 16:19]
it is the address I found here: https://loomx.io/developers/docs/en/testnet-plasma.html#contract-addresses-transfer-gateway

Pierre, [19.06.19 16:19]
but looks like the last tx was 90 days ago

Nayeem | Loom Network, [19.06.19 16:21]
[In reply to Pierre]
hey checking sec

Pierre, [19.06.19 16:21]
seems like the right address is 0xE080079Ac12521D57573f39543e1725EA3E16DcC

Pierre, [19.06.19 16:21]
you should update your website

Matthew Campbell, [19.06.19 16:22]
@nayeemsidd can you add a ticket on the docs site and get andrei to fix this

**Comment by Nayeem1516** [comment]
Hmm after having a discussion with Andrei - we think we need to find a automatic process so that whenever these addresses are changed will be updated in our docs or anywhere so that we can pick from there. Will look into it.

**Comment by mattkanwisher** [comment]
Seems like old docs are on /developers/docs/ and we need to redirect it to /developers

**Comment by mattkanwisher** [comment]
fixed I now redirect /developers/docs -> /developers
