### ISSUE TITLE
Check if https://loomx.io/developers/en/loom-yaml.html#loom-yaml needs to be updated

### ISSUE THREAD

**Issue by andreipope** [loomnetwork/loom-sdk-documentation#319]
Check if https://loomx.io/developers/en/loom-yaml.html#loom-yaml needs to be updated as per https://t.me/loomnetwork/125537

**Comment by mattkanwisher** [comment]
it seems like some docs are referencing RPCListenAddress make sure this is consistent? is this used anymore

**Comment by andreipope** [comment]
PR: https://github.com/loomnetwork/loom-sdk-documentation/pull/334
