### ISSUE TITLE
Update the loom-js quick start to call Solidity contract

### ISSUE THREAD

**Issue by HangYang** [loomnetwork/loom-sdk-documentation#365]
In current version, it's trying to call a Golang contract. 
Update it to a Solidity contract example

**Comment by andreipope** [comment]
@HangYang I'll take this over. I'm pretty familiar with the `truffle-dappchain-example` repo so it won't take me too much to update it.

**Comment by andreipope** [comment]
PR: https://github.com/loomnetwork/loom-sdk-documentation/pull/366
