### ISSUE TITLE
Loom not downloading with curl on WSL

### ISSUE THREAD

**Issue by thaDev404** [loomnetwork/loom-sdk-documentation#386]
On running "curl https://raw.githubusercontent.com/loomnetwork/loom-sdk-documentation/master/scripts/get_loom.sh | sh && chmod +x loom", from my bash i get the following message

Downloading loom executable...
chmod: cannot access 'loom': No such file or directory
sh: 23: ./loom: not found
All done.
chmod: cannot access 'loom': No such file or directory

**Comment by adyromantika** [comment]
Could you please try running from the branch from the PR above

```bash
https://raw.githubusercontent.com/loomnetwork/loom-sdk-documentation/update-download-script/scripts/get_loom.sh | bash
```

**Comment by thaDev404** [comment]
works just fine, thanks for your swift response.
