### ISSUE TITLE
Sidebar is showing Chinese 

### ISSUE THREAD

**Issue by HangYang** [loomnetwork/loom-sdk-documentation#63]
![image](https://user-images.githubusercontent.com/3389447/40955048-40a28c74-68ba-11e8-947b-f6327e095bf8.png)

**Comment by mattkanwisher** [comment]
bug in the framework, waiting for this PR to merge https://github.com/facebook/Docusaurus/pull/709#issuecomment-394274777

**Comment by mattkanwisher** [comment]
fixed in temporary build
@skogman can you look at moving to master https://github.com/facebook/Docusaurus/pull/705
