### ISSUE TITLE
Typo in "Javascript WebSockets and Web3 Demo"

### ISSUE THREAD

**Issue by danielrw7** [loomnetwork/loom-sdk-documentation#75]
In `docs/phaser-sdk-demo-websocket-web3.md` and `website/translated_docs/zh-CN/phaser-sdk-demo-websocket-web3.md`

>to create seamlessly experience

should be 

>to create seamless experiences

or

>to create a seamless experience

**Comment by mattkanwisher** [comment]
fixed thx
