### ISSUE TITLE
link for EVM is not right

### ISSUE THREAD

**Issue by HangYang** [loomnetwork/loom-sdk-documentation#77]
in this page : https://loomx.io/developers/docs/en/web3js-loom-provider-truffle.html. In the `Overview`, The link for `EVM` page is 404.
it should be `https://loomx.io/developers/docs/en/evm.html`
white it is `https://loomx.io/developers/docs/en/docs/en/evm.html` now, with an extra `docs/en/`

**Comment by mattkanwisher** [comment]
fixed, in future can you open a PR

**Comment by HangYang** [comment]
sure
