### ISSUE TITLE
Add documentation for writing smart contracts in Go

### ISSUE THREAD

**Issue by MidnightLightning** [loomnetwork/loom-sdk-documentation#98]
On the "Building DAppChain clients in Golang" page (`go-loom-clients`), the documentation currently indicates:

> In this section you'll be introduced to the go-loom API that you will use to write Go code that interacts with a Loom DAppChain, writing smart contracts in Go will be covered in a later section.

That "writing smart contracts in Go" bit I can't find in the existing documentation. Does it exist or need to be created yet? The [`helloworld`](https://github.com/loomnetwork/go-loom/blob/master/examples/plugins/helloworld/helloworld.go) sample contract written in Go has some examples of needed syntax, but the deployment and other nuances of a Go contract don't seem to be covered.

**Comment by mattkanwisher** [comment]
Yeah I can write more. The weave-blueprint repo is an end to end example in Go. The deployment is done via a genesis file. Check that repo and see what questions you have

**Comment by mattkanwisher** [comment]
This is quite old, we have released a few others since, like the Etherboy repo. Please feel free to reopen if you still think this is an issue
